### ISSUE TITLE
Windows - pressing a character throws exception

### ISSUE THREAD

**Issue by matkuki** [paranim/pvim#1] opened 2020-03-19 16:33 UTC
Pressing any character other than '**:**' on the startup screen, throws this:
```
fatal.nim(49)            sysFatal
Error: unhandled exception: value out of range: 1 notin -2147483648 .. 2147483647 [RangeError]
```

Specs:
- Windows 10 x64
- Nim Devel

**Comment by oakes** [comment] 2020-03-19 16:35
Is it only happening on devel for you? i'm on 1.0.6 with windows 10 and haven't seen that error.

**Comment by matkuki** [comment] 2020-03-19 17:00
I only use devel, yes. To be sure I rebuilt Nim again, but the exception persists.

**Comment by oakes** [comment] 2020-03-19 17:04
Ok i reproduced it. I'm guessing this is a bug in devel, since 1 is most definitely between `-2147483648 .. 2147483647`. I'll try to see if i can track down a minimal example that throws the error.

**Comment by oakes** [comment] 2020-03-19 17:20
I think i narrowed it down: https://github.com/nim-lang/Nim/issues/13698

**Comment by oakes** [comment] 2020-03-20 13:50
This is fixed on the latest devel.

**Closed as completed by oakes** 2020-03-20 13:50 UTC
